### ISSUE TITLE
로그인 및 회원가입 유효성 검사 구현

### ISSUE THREAD

**Issue by esoby** [esoby/e-commerce#5]
## 📚 Description 

로그인 및 회원가입 유효성 검사 구현
유효하지 않은 입력에 대한 피드백으로 사용자 경험 향상
- Firebase의 이메일 중복 체크 및 형식 검사 기능을 활용
- 비밀번호 전자인증 가이드라인 (NIST) 에 따라 규칙 적용

## 📝 TODO 

- [x] 로그인 실패 시 피드백
- [x] 회원가입 실패 시 실패 유형별 안내
- [x] 비밀번호 유효성 검사 추가
